#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: noname
 * Date: 29.10.18
 * Time: 11:35
 */

use app\ConsoleHelper;
use yii\helpers\ArrayHelper;

require __DIR__ . '/vendor/autoload.php';

ConsoleHelper::fillLine('Init');

$configPath = __DIR__ . '/config/';
$scriptsPath = __DIR__ . '/scripts/';

$projectDefault = '';
$dirDefault = '';

if (file_exists($configPath . 'main.php')) {
    $config = require $configPath . 'main.php';
    $projectDefault = ArrayHelper::getValue($config, 'default.project');
    $dirDefault = ArrayHelper::getValue($config, 'default.dir');
    unset($config);
    unlink($configPath . 'main.php');
}

$dir = ConsoleHelper::readParams('project dir', $dirDefault);
$project = ConsoleHelper::readParams('project name', $projectDefault);

$config = file_get_contents($configPath . 'main.php.sample');
$config = str_replace('{%project%}', $project, $config);
$config = str_replace('{%dir%}', $dir, $config);

file_put_contents($configPath . 'main.php', $config);
if (!file_exists($configPath . 'components.php')) {
    copy($configPath . 'components.php.sample', $configPath . 'components.php');
}

$sampleScripts = scandir($scriptsPath);
$done = 0;
$total = count($sampleScripts);
$copyCount = 0;
$drop = ConsoleHelper::readParams('drop scripts', 'Y/n');

if ($drop === '' || strtolower($drop) === 'y') {
    foreach ($sampleScripts as $file) {
        if (preg_match('/.\.yaml/', $file)) {
            unlink($file);
        }
    }
}

\yii\helpers\Console::startProgress($done, $total, 'copy scripts');
foreach ($sampleScripts as $file) {
    \yii\helpers\Console::updateProgress(++$done, $total);
    if (preg_match('/.\.sample/', $file)) {
        $fileName = substr($file, 0, strlen($file) -7 );
        if (!file_exists($scriptsPath . $fileName)) {
            copy($scriptsPath . $file, $scriptsPath . $fileName);
            $copyCount++;
        }
    }
}
\yii\helpers\Console::endProgress();
ConsoleHelper::writeln('count copy scripts: [' . $copyCount . ']');

ConsoleHelper::fillLine('Complete.');