#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: noname
 * Date: 29.10.18
 * Time: 11:35
 */

use app\ConsoleHelper;
use yii\helpers\ArrayHelper;

require __DIR__ . '/vendor/autoload.php';

ConsoleHelper::fillLine('Init');

$configPath = __DIR__ . '/config/';

$projectDefault = '';
$projectDir = '';

if (file_exists($configPath . 'main.php')) {
    $config = require $configPath . 'main.php';
    $projectDefault = ArrayHelper::getValue($config, 'default.project');
    $dirDefault = ArrayHelper::getValue($config, 'default.dir');
    unset($config);
    unlink($configPath . 'main.php');
}

$dir = ConsoleHelper::readParams('project dir', $projectDefault);
$project = ConsoleHelper::readParams('project name', $dirDefault);

$config = file_get_contents($configPath . 'main.php.sample');
$config = str_replace('{%project%}', $project, $config);
$config = str_replace('{%dir%}', $dir, $config);

file_put_contents($configPath . 'main.php', $config);

copy($configPath . 'components.php.sample', $configPath . 'components.php');

ConsoleHelper::fillLine('Complete.');